# SITE CONFIGURATION
title: Birkenbach-Oremus Lab: FishBOL UD # your site title
author: abirken # You :P
description: > # Meta description of Homepage
  My intial attempt at a GitHub Page.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://abirken.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://www.linkedin.com/in/annabirkenbach
    - https://github.com/abirken

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Research', link: '/research'}
  - {name: 'Students', link: '/students'}
  - {name: 'News', link: '/labnews'}
  - {name: 'Contact', link: '/contact'}

tagline:
  Data-driven marine resource economics and policy research at the University of Delaware

hero_img: posts/fishbol.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: abirken@udel.edu # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  abirken # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
